name: Waka Readme

on:
  schedule:
    - cron: "0 12 * * *" # every day at 12pm
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL_CODE_TIME: true
          SHOW_LANGUAGE: true
          SHOW_OS: true
          SHOW_PROJECTS: true
